# frozen_string_literal: true

source 'https://rubygems.org'

gem 'daemons', require: false
gem 'delayed_job'
gem 'delayed_job_active_record'
gem 'pg'
gem 'rack'
gem 'webrick'
gem 'yabeda-delayed_job', path: '/gem'
gem 'yabeda-prometheus'
