{
 "title": "Delayed Job",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max (delayed_job_queue_latency) by (queue)"
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max (delayed_job_jobs_waiting_count) by (queue)",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Enqueue rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(delayed_job_jobs_enqueued_total[5m])) by (queue, worker)",
     "legendFormat": "{{ queue }}/{{ worker }}"
    }
   ]
  },
  {
   "title": "Error/Fail rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(delayed_job_jobs_errored_total[5m])) by (worker)",
     "legendFormat": "{{ worker }}"
    },
    {
     "expr": "sum (rate(delayed_job_jobs_failed_total[5m])) by (worker)"
    }
   ]
  },
  {
   "title": "Job runtime 95q",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, worker) (rate(delayed_job_job_runtime_seconds_bucket[5m])))",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Current job runtime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max (delayed_job_running_job_runtime_seconds) by (worker)",
     "legendFormat": "{{ worker }}"
    }
   ]
  }
 ]
}