{
 "title": "Sidekiq Memory Profiler",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Memory Allocation (per queue, worker)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sidekiq_total_allocated_memsize) by (queue, worker) / sum(sidekiq_jobs_success_total) by (queue, worker)",
     "legendFormat": "{{ queue }}\\{{worker}}"
    }
   ]
  },
  {
   "title": "Allocated/Retained Memory (per queue, worker)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_total_allocated_memsize[1m])) by (queue, worker)",
     "legendFormat": "{{ queue }}\\{{ worker }}: allocated memory"
    },
    {
     "expr": "sum(rate(sidekiq_total_retained_memsize[1m])) by (queue, worker)",
     "legendFormat": "{{ queue }}\\{{ worker }}: retained memory"
    }
   ]
  },
  {
   "title": "Memory Usage (per instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum (memory_usage) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}